const DUPLICATE_LINE = 'DUPLICATE_LINE';
const NEXT_LESSON = 'NEXT_LESSON';
const UPDATE_STATUS = 'UPDATE_STATUS';
const UPDATE_MODAL_STATUS = 'UPDATE_MODAL_STATUS';

export {
    DUPLICATE_LINE,
    NEXT_LESSON,
    UPDATE_STATUS,
    UPDATE_MODAL_STATUS,
};
